# Generated by Django 4.1 on 2022-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfosTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("date", models.CharField(max_length=12)),
                ("value", models.FloatField()),
                ("cpf", models.PositiveBigIntegerField()),
                ("card", models.CharField(max_length=12)),
                ("hour", models.CharField(max_length=12)),
                ("owner", models.CharField(max_length=14)),
                ("store", models.CharField(max_length=19)),
            ],
        ),
    ]
