# Generated by Django 4.1 on 2022-10-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cnabs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Infos",
            new_name="InfosTable",
        ),
    ]
